# To create containers, run "docker-compose up --build" in the parent directory

version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5001:5001'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mongodb+srv://user:password@cluster0.lielach.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend
